services:
  # Servidor MQTT (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - iot-network
    restart: unless-stopped

  # Simulador de sensores IoT
  sensor-simulator:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: iot-sensor-simulator
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC_PREFIX=sensors
      - SENSOR_INTERVAL=1
    depends_on:
      - mosquitto
    networks:
      - iot-network
    restart: unless-stopped

networks:
  iot-network:
    name: iot-network
    external: true

volumes:
  mosquitto-data:
  mosquitto-log:

 