services:
  # Servidor MQTT (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - iot-network
    restart: unless-stopped

  # Simulador de sensores IoT
  sensor-simulator:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: iot-sensor-simulator
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC_PREFIX=sensors
      - SENSOR_INTERVAL=1
    depends_on:
      - mosquitto
    networks:
      - iot-network
    restart: unless-stopped

  # MongoDB para armazenamento de dados históricos (Time Series)
  mongodb:
    image: mongo:7.0
    container_name: timeseries-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=aas_timeseries
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - iot-network
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 1.5

  # Mongo Express (Interface Web para MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-ui
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - iot-network
    restart: unless-stopped

  # Time Series Recorder - Grava dados históricos em MongoDB
  timeseries-recorder:
    build:
      context: ../app
      dockerfile: Dockerfile.timeseries
    container_name: timeseries-recorder
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC_PREFIX=sensors
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin123
      - MONGO_DB=aas_timeseries
    depends_on:
      - mosquitto
      - mongodb
    networks:
      - iot-network
    restart: unless-stopped

networks:
  iot-network:
    name: iot-network
    external: true

volumes:
  mosquitto-data:
  mosquitto-log:
  mongodb-data:
  mongodb-config:
